CRITICAL - 2021-02-22 12:23:12 --> Undefined property: App\Controllers\Trabajos::$validation
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Trabajos.php(193): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 193, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Trabajos->store()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Trabajos))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 13:00:39 --> Undefined variable: errors
#0 C:\xampp\htdocs\Dymstudio\app\Views\Admin\mantenimientos\trabajos\create.php(11): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 11, Array)
#1 C:\xampp\htdocs\Dymstudio\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\Dymstudio\system\Common.php(1087): CodeIgniter\View\View->render('Admin/mantenimi...', Array, true)
#3 C:\xampp\htdocs\Dymstudio\app\Controllers\Trabajos.php(19): view('Admin/mantenimi...', Array)
#4 C:\xampp\htdocs\Dymstudio\app\Controllers\Trabajos.php(163): App\Controllers\Trabajos->loadViews('mantenimientos/...', Array)
#5 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Trabajos->create()
#6 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Trabajos))
#7 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-02-22 13:19:27 --> Undefined property: App\Controllers\Trabajos::$validation
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Trabajos.php(185): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 185, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Trabajos->store()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Trabajos))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 13:21:33 --> Undefined property: App\Controllers\Trabajos::$validation
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Trabajos.php(184): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined prope...', 'C:\\xampp\\htdocs...', 184, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Trabajos->store()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Trabajos))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 18:25:05 --> Undefined variable: data
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(32): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 32, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->login()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 18:26:59 --> Call to a member function listErrors() on string
#0 C:\xampp\htdocs\Dymstudio\system\View\View.php(246): include()
#1 C:\xampp\htdocs\Dymstudio\system\Common.php(1087): CodeIgniter\View\View->render('Admin/login', Array, true)
#2 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(33): view('Admin/login', Array)
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->login()
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-22 18:49:05 --> Call to undefined method CodeIgniter\Validation\Validation::listError()
#0 C:\xampp\htdocs\Dymstudio\system\View\View.php(246): include()
#1 C:\xampp\htdocs\Dymstudio\system\Common.php(1087): CodeIgniter\View\View->render('Admin/login', Array, true)
#2 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(33): view('Admin/login', Array)
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->login()
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-22 20:07:36 --> Encrypter needs a starter key.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Encryption.php(155): CodeIgniter\Encryption\Exceptions\EncryptionException::forNeedsStarterKey()
#1 C:\xampp\htdocs\Dymstudio\system\Config\Services.php(234): CodeIgniter\Encryption\Encryption->initialize(Object(Config\Encryption))
#2 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(78): CodeIgniter\Config\Services::encrypter()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2021-02-22 20:09:33 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(128): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('?\xD3\x88???\x07?tS<??\fh...')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->postlogin()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:13:16 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(128): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('?<\x130?UT,nf??zg?...')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->postlogin()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:23:58 --> Undefined variable: totalTime
#0 C:\xampp\htdocs\Dymstudio\system\Debug\Toolbar\Views\toolbar.tpl.php(56): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 56, Array)
#1 C:\xampp\htdocs\Dymstudio\system\Debug\Toolbar.php(498): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\Dymstudio\system\Debug\Toolbar.php(455): CodeIgniter\Debug\Toolbar->format(Array, 'html')
#3 C:\xampp\htdocs\Dymstudio\app\Config\Events.php(44): CodeIgniter\Debug\Toolbar->respond()
#4 [internal function]: CodeIgniter\Events\Events::Config\{closure}()
#5 C:\xampp\htdocs\Dymstudio\system\Events\Events.php(188): call_user_func(Object(Closure))
#6 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(289): CodeIgniter\Events\Events::trigger('pre_system')
#7 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-02-22 20:29:33 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(141): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('?e???\x07?\x1FNv**?P~...')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->postlogin()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:31:17 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(141): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('?e???\x07?\x1FNv**?P~...')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->postlogin()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:42:55 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(101): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:43:17 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(101): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('3H8pgJSxNreMA6F...')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:43:37 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(101): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('WRQDEWUi0wu96c+...')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:43:56 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(101): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('yECJaEtCNE3pCr0...')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:45:12 --> Undefined variable: joe.doe@example.com
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 20:45:14 --> Undefined variable: joe.doe@example.com
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 20:45:15 --> Undefined variable: joe.doe@example.com
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 20:45:16 --> Undefined variable: joe.doe@example.com
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(105): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 105, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 20:50:33 --> Decrypting: authentication failed.
#0 C:\xampp\htdocs\Dymstudio\system\Encryption\Handlers\OpenSSLHandler.php(159): CodeIgniter\Encryption\Exceptions\EncryptionException::forAuthenticationFailed()
#1 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(101): CodeIgniter\Encryption\Handlers\OpenSSLHandler->decrypt('lrJx96ZM1px6Ia9...')
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->create_user()
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#5 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#6 {main}
CRITICAL - 2021-02-22 20:57:07 --> Trying to get property 'id' of non-object
#0 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(152): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 152, Array)
#1 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->postlogin()
#2 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2021-02-22 20:59:55 --> Trying to get property 'firstname' of non-object
#0 C:\xampp\htdocs\Dymstudio\app\Views\Admin\layout\header.php(21): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 21, Array)
#1 C:\xampp\htdocs\Dymstudio\app\Views\Admin\dashboard.php(8): include_once('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\Dymstudio\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Dymstudio\system\Common.php(1087): CodeIgniter\View\View->render('Admin/dashboard', Array, true)
#4 C:\xampp\htdocs\Dymstudio\app\Controllers\Home.php(34): view('Admin/dashboard', Array)
#5 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Home->dashboard()
#6 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2021-02-22 22:05:09 --> Call to a member function listErrors() on string
#0 C:\xampp\htdocs\Dymstudio\system\View\View.php(246): include()
#1 C:\xampp\htdocs\Dymstudio\system\Common.php(1087): CodeIgniter\View\View->render('Admin/forgot_pa...', Array, true)
#2 C:\xampp\htdocs\Dymstudio\app\Controllers\Users.php(439): view('Admin/forgot_pa...', Array)
#3 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(914): App\Controllers\Users->forgot_password()
#4 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#5 C:\xampp\htdocs\Dymstudio\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\Dymstudio\public\index.php(45): CodeIgniter\CodeIgniter->run()
#7 {main}
